# -- Site Configuration --
# slightlysimple - Tech Tips Blog
# Refer to Congo theme docs: https://jpanther.github.io/congo/docs/

theme = "congo"
baseURL = "https://slightlysimple.net"
defaultContentLanguage = "ja"
title = "slightlysimple"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true