[[main]]
  name = "ホーム"
  pageRef = "/"
  weight = 10

[[main]]
  name = "記事"
  pageRef = "/posts"
  weight = 20

[[main]]
  name = "カテゴリ"
  pageRef = "/categories"
  weight = 30

[[main]]
  name = "タグ"
  pageRef = "/tags"
  weight = 40

[[main]]
  name = "About"
  pageRef = "/about"
  weight = 50

[[main]]
  name = "お問い合わせ"
  pageRef = "/contact"
  weight = 60

[[main]]
  name = "プライバシーポリシー"
  pageRef = "/privacy"
  weight = 70

[[main]]
  name = "運営者情報"
  pageRef = "/operator"
  weight = 80