[[main]]
  name = "ホーム"
  pageRef = "/"
  weight = 10

[[main]]
  name = "記事"
  pageRef = "/posts"
  weight = 20

[[main]]
  name = "カテゴリ"
  pageRef = "/categories"
  weight = 30

[[main]]
  name = "タグ"
  pageRef = "/tags"
  weight = 40

[[main]]
  name = "About"
  pageRef = "/about"
  weight = 50